---
title: "Tidying data from Smartphone Accelerometers"
author: "Maxim Shayduk"
date: "January 10, 2016"
output: 
  html_document:
    keep_md: true
---

### Synopsis ###
The goal of this project is to demonstrate how to process the fragmented raw data and transform it to a single **tidy** data-set that can be used for later analysis.  The  principles of **tidy** data are described [this paper](http://vita.had.co.nz/papers/tidy-data.pdf>). 

###Data###

The raw data-set is the data collected from the accelerometers of the Samsung Galaxy S smartphone. This data-set contains multiple .txt files  with variables labels, variables descriptions and multiple files with observational data. 

The data was collected over a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six Activities wearing a smartphone (Samsung Galaxy S II) on the waist. The Activities categories are: 

  1. WALKING, 
  2. WALKING_UPSTAIRS, 
  3. WALKING_DOWNSTAIRS, 
  4. SITTING, 
  5. STANDING, 
  6. LAYING.

During these activities the data from the smartphone accelerometers was recorded and processed resulting in 561-dimentional feature vector. A full description of the data-set is available at: 
 <http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones> and in the README.txt file.
The data-set can be  downloaded from <http://archive.ics.uci.edu/ml/machine-learning-databases/00240/UCI%20HAR%20Dataset.zip> and should be placed in the working directory. 
As of January 16, 2016, the unzipped data-set includes following files:

- './README.txt':  Detailed description of the data-set

- './features_info.txt': Information about the variables used on the feature vector.
- './features.txt': List of all features (561 features names).
- './activity_labels.txt': Descriptive Activity labels (six number-name pairs).

- './train/subject_train.txt': Volunteers's IDs in the train set (30 unique values).
- './train/X_train.txt': Training set (observations of 561 features).
- './train/y_train.txt': Training Activity category labels (6 unique values).
- './train/Inertial Signals/': Directory with sensors data from which the features were extracted.


- './test/subject_test.txt': Volunteers's IDs in the test set (30 unique values).
- './test/X_test.txt': Test set (observations of 561 features).
- './test/y_test.txt': Test  Activity category labels (6 unique values).
- './test/Inertial Signals/': Directory with sensors data from which the features were extracted.

### Project files###

The project comprises:

  1. Analysis script: **run_analysis.R**.
  2. Tidy data set:  **UCI_HAR_tidy.txt**
  3. Code book: **CodeBook.md**.

#### run_analysis.R ####

This script reads the .zip file in the working directory, binds the observations of all variables in one data.table, assigns a descriptive variable names, subsets data by a list of selected varables and saves a tidy data-set to the **UCI_HAR_tidy.txt** file.

#### UCI_HAR_tidy.txt ####

This is the output of the analysis script: a tidy data-set with descriptive variable names and reduced number of variables (as compared to the initial data).

#### CodeBook.md ####  
 This markdown file describes the initial data-set, the variables, transformations performed to clean up the data and the final tidy data-set saved in **UCI_HAR_tidy.txt**.